/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author drewk
 */
public class Graph extends javax.swing.JFrame {

    /**
     * Creates new form Graph
     */
   Reading reading = new Reading();
    
    public Graph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel78 = new javax.swing.JPanel();
        tab1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tab3 = new javax.swing.JLabel();
        jPanel0 = new javax.swing.JPanel();
        tab2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(54, 33, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CraterWater");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 86));

        jPanel78.setBackground(new java.awt.Color(54, 33, 89));
        jPanel78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel78MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel78MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel78MouseEntered(evt);
            }
        });

        tab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tab1.setForeground(new java.awt.Color(255, 255, 255));
        tab1.setText("Daily Performance");
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tab1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel78Layout = new javax.swing.GroupLayout(jPanel78);
        jPanel78.setLayout(jPanel78Layout);
        jPanel78Layout.setHorizontalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel78Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel78Layout.setVerticalGroup(
            jPanel78Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel78Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tab1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 430, 130));

        jPanel6.setBackground(new java.awt.Color(54, 33, 89));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        tab3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tab3.setForeground(new java.awt.Color(255, 255, 255));
        tab3.setText("Further Readings");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab3)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tab3)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 430, -1));

        jPanel0.setBackground(new java.awt.Color(85, 65, 118));
        jPanel0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel0MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel0MouseEntered(evt);
            }
        });

        tab2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tab2.setForeground(new java.awt.Color(255, 255, 255));
        tab2.setText("Graphical Analysis");

        javax.swing.GroupLayout jPanel0Layout = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(jPanel0Layout);
        jPanel0Layout.setHorizontalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab2)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel0Layout.setVerticalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(tab2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 430, 120));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 20));

        jLabel1.setText(".");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 860, 40, -1));

        jPanel2.setBackground(new java.awt.Color(103, 78, 140));

        jTable1.setBackground(new java.awt.Color(85, 65, 118));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Double(1.0),  new Double(7.2),  new Double(7.89),  new Double(1.67),  new Double(5.73)},
                { new Double(2.0),  new Double(7.21),  new Double(7.86),  new Double(1.31),  new Double(5.44)},
                { new Double(3.0),  new Double(7.24),  new Double(7.81),  new Double(1.25),  new Double(5.55)},
                { new Double(4.0),  new Double(7.49),  new Double(7.89),  new Double(1.17),  new Double(5.67)},
                { new Double(5.0),  new Double(7.51),  new Double(7.86),  new Double(1.33),  new Double(5.65)},
                { new Double(6.0),  new Double(7.43),  new Double(7.81),  new Double(1.56),  new Double(5.82)},
                { new Double(7.0),  new Double(7.42),  new Double(7.84),  new Double(1.68),  new Double(5.93)},
                { new Double(8.0),  new Double(7.47),  new Double(7.85),  new Double(1.83),  new Double(6.54)},
                { new Double(9.0),  new Double(7.53),  new Double(7.86),  new Double(1.94),  new Double(6.38)},
                { new Double(10.0),  new Double(7.54),  new Double(7.88),  new Double(1.97),  new Double(6.27)},
                { new Double(11.0),  new Double(7.51),  new Double(7.73),  new Double(2.53),  new Double(6.74)},
                { new Double(12.0),  new Double(7.43),  new Double(7.82),  new Double(2.42),  new Double(6.32)},
                { new Double(13.0),  new Double(7.39),  new Double(7.77),  new Double(2.31),  new Double(6.54)},
                { new Double(14.0),  new Double(7.38),  new Double(7.73),  new Double(2.26),  new Double(6.67)},
                { new Double(15.0),  new Double(7.42),  new Double(7.87),  new Double(2.18),  new Double(6.64)},
                { new Double(16.0),  new Double(7.39),  new Double(7.72),  new Double(2.19),  new Double(6.82)},
                { new Double(17.0),  new Double(7.41),  new Double(7.87),  new Double(2.44),  new Double(6.37)},
                { new Double(18.0),  new Double(7.43),  new Double(7.92),  new Double(2.22),  new Double(6.54)},
                { new Double(19.0),  new Double(7.44),  new Double(7.94),  new Double(2.13),  new Double(6.63)},
                { new Double(20.0),  new Double(7.44),  new Double(7.87),  new Double(1.75),  new Double(6.57)},
                { new Double(21.0),  new Double(7.44),  new Double(7.79),  new Double(1.86),  new Double(6.52)},
                { new Double(22.0),  new Double(7.29),  new Double(7.72),  new Double(1.98),  new Double(6.34)},
                { new Double(23.0),  new Double(7.32),  new Double(7.74),  new Double(2.64),  new Double(6.16)},
                { new Double(24.0),  new Double(7.35),  new Double(7.87),  new Double(2.52),  new Double(6.01)},
                { new Double(25.0),  new Double(7.35),  new Double(7.72),  new Double(2.41),  new Double(5.92)},
                { new Double(26.0),  new Double(7.34),  new Double(7.84),  new Double(2.35),  new Double(5.83)},
                { new Double(27.0),  new Double(7.31),  new Double(7.84),  new Double(2.67),  new Double(5.64)},
                { new Double(28.0),  new Double(7.28),  new Double(7.83),  new Double(2.38),  new Double(5.68)},
                { new Double(29.0),  new Double(7.25),  new Double(7.72),  new Double(2.39),  new Double(5.76)},
                { new Double(30.0),  new Double(7.21),  new Double(7.81),  new Double(2.55),  new Double(5.92)},
                { new Double(31.0),  new Double(7.31),  new Double(7.81),  new Double(2.44),  new Double(6.11)}
            },
            new String [] {
                "Day", "pH", "Dissolved Oxygen (g/mL)", "Turbidity (NTU*10^1)", "Specific Conductance (10^2*S/m)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monthly Performance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 830, 880));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseEntered
        tab1.setBackground(new java.awt.Color(85, 65, 118));
    }//GEN-LAST:event_tab1MouseEntered

    private void jPanel78MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel78MouseExited
        jPanel78.setBackground(new java.awt.Color(54,33,89));
    }//GEN-LAST:event_jPanel78MouseExited

    private void jPanel78MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel78MouseEntered
        jPanel78.setBackground(new java.awt.Color(85, 65, 118));
    }//GEN-LAST:event_jPanel78MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new java.awt.Color(54,33,89));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new java.awt.Color(85, 65, 118));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel0MouseExited
        
    }//GEN-LAST:event_jPanel0MouseExited

    private void jPanel0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel0MouseEntered
      
    }//GEN-LAST:event_jPanel0MouseEntered

    private void jPanel78MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel78MouseClicked
      
    }//GEN-LAST:event_jPanel78MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        reading.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tab1;
    private javax.swing.JLabel tab2;
    private javax.swing.JLabel tab3;
    // End of variables declaration//GEN-END:variables

    private static class DefaultCategoryDataset {

        public DefaultCategoryDataset() {
        }

        private void setValue(int i, String test, String test0) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

}
